:type: plugin
:status: published
:title: Audit Controlled Access Plugin
:link: _audit_controlled_access_plugin
:plugintypes: postquery
:summary: Audits controlled access based off specific metacard attributes and configured values.

This plugin audits when a controlled metacard is being accessed.
The determination for whether a metacard is controlled is based on configurable values for the attributes Classification, Releasability, DisseminationControls, and Codewords.
If any of the configured values match the respective attribute value(s) on the metacard, the metacard is audited.

===== Installing Audit Controlled Access Plugin

The Audit Controlled Access Plugin is not installed by default in a standard installation in the ${alliance-security} application.

To install:

. Navigate to the *${admin-console}*.
. Select the *System* tab.
. Select the *Features* tab.
. Install the `security-auditcontrolledaccess` feature.

===== Configuring Audit Controlled Access Plugin

To configure the Audit Controlled Access Plugin:

. Navigate to the *${admin-console}*.
. Select the *${alliance-security}* application.
. Select *Configuration* tab.
. Select *Audit Controlled Access Plugin*.

See <<{reference-prefix}org.codice.alliance.catalog.plugin.auditcontrolled.AuditControlledAccessPlugin,Audit Controlled Access Plugin configurations>> for all possible configurations.

